# IMPORTING THE LIBRARY

In [1]:
import pandas as pd
import numpy as np

# LOADING THE DATA SET

In [2]:
df=pd.read_csv('add.csv')

In [3]:
df.head()

x     y   sum
0   1.0   1.0   2.0
1   4.0   4.0   8.0
2   6.0   6.0  12.0
3  10.0  10.0  20.0
4  30.0  30.0  60.0

# SAPERATE THE INDEPENDENT VARIABLE AND TRAGET VARIABLE

In [5]:
x=df.iloc[:,0:2]
y=df.iloc[:,-1]

# TRAIN TEST SPLIT OPERATION

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)

# TRAIN THE MODEL ON TRAINING SET

In [9]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()


In [10]:
#training the model using fit function
model.fit(x_train,y_train)

LinearRegression()

# PREDICTION

In [13]:
y_pred=model.predict(x_test)

In [14]:
y_pred

array([  2. , 135. ,  68. , 169.4, 155.7,  66. ,   8. , 271.5,  12. ])

In [17]:
print(model.predict([[10,20]]))

[30.]


In [18]:
print(model.predict([[36,90.5]]))

[126.5]


# SAVE MODEL USING JOBLIB

In [19]:
import joblib
joblib.dump(model,'model_joblib')
model=joblib.load('model_joblib')
model.predict([[30,40]])

array([70.])

# GUI

# FIRSTLY TRAIN WITH COMPLETE DATA SET

In [20]:
x=df.iloc[:,0:2]
y=df.iloc[:,-1]

In [21]:
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [22]:
import joblib
joblib.dump(model,'model_joblib')
model=joblib.load('model_joblib')

In [23]:
model.predict([[30,40]])


array([70.])

# GUI CREATION

In [ ]:
from tkinter import * 
import joblib
def show_entry_fields():
    p1=float(e1.get())
    p2=float(e2.get())
    model=joblib.load('model_joblib')
    result=model.predict([[p1,p2]])
    Label(master,text='sum is = ').grid(row=4)
    Label(master,text=result).grid(row=5)
    print("sum is",result)
master=Tk()
master.title("Addition of two numbers using ml")
label=Label(master,text="Addition of two numbers using ml",bg='black',fg='white').grid(row=0,columnspan=2)
Label(master,text="Enter first number").grid(row=1)
Label(master,text="Enter second number").grid(row=2)
e1=Entry(master)
e2=Entry(master)
e1.grid(row=1,column=1)
e2.grid(row=2,column=1)
Button(master,text='predict',command=show_entry_fields).grid()
mainloop()


sum is [121.]
